#!/bin/sh

set -e 

PARENT_DIR=/var/lib/lightdm/.config
CONFIG_DIR=${PARENT_DIR}/deepin

if [ "$1" = "configure" ];then
	[ -d $CONFIG_DIR ] || mkdir -p $CONFIG_DIR
	if id -u lightdm >/dev/null 2>&1; then
		chown -R lightdm:lightdm $PARENT_DIR
	fi

	update-alternatives --install /usr/share/xgreeters/lightdm-greeter.desktop \
	lightdm-greeter /usr/share/xgreeters/lightdm-deepin-greeter.desktop 90
fi

#DEBHELPER#
exit 0
