#!/bin/sh

set -e

if [ "$1" = "configure" ];then
	update-alternatives --install /usr/share/xgreeters/lightdm-greeter.desktop \
	lightdm-greeter /usr/share/xgreeters/lightdm-deepin-greeter.desktop 90
fi

#DEBHELPER#
# determine dde-lock process is existed
ProcNumber=$(pgrep -f dde-lock | wc -l)

# dde-shutdown not exist after the system upgrade, we need to restart dde-lock process
if [ ! -f /usr/bin/dde-shutdown ] && [ "$ProcNumber" -gt 0 ] ; then
	pkill -ef dde-lock
fi
exit 0
