#!/bin/bash
display_daemon="/usr/lib/deepin-daemon/greeter-display-daemon"
if [ -x $display_daemon ]; then
    $display_daemon &
fi

export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/plugins/platforms
export QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins
export QML2_IMPORT_PATH=/usr/lib/x86_64-linux-gnu/qt5/qml
export XDG_DATA_DIRS=/usr/share
export XDG_CURRENT_DESKTOP=Deepin
export QT_DEBUG_PLUGINS=1

# greeter没正常退出的情况下，会重新拉起greeter
start_lightdm_deepin_greeter() {
  echo "-lightdm-deepin-greeter starting..." 1>&2
  while true; do
      /usr/bin/lightdm-deepin-greeter
      exit_status=$?
      if [ $exit_status -eq 0 ]; then
          break
      else
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$current_time: -lightdm-deepin-greeter exited with non-zero status. Restarting..." 1>&2
      fi
  done
}

dde-dconfig --get -a org.deepin.dde.lightdm-deepin-greeter -r org.deepin.dde.lightdm-deepin-greeter -k enableLighterGreeter | grep "true"
if [ $? -eq 0 ];then
    /usr/bin/lightdm-deepin-greeter-lighter

    # 没正常退出的情况下，仍然拉起原版Greeter
    if [ $? -ne 0 ];then
        start_lightdm_deepin_greeter
    fi
else
    start_lightdm_deepin_greeter
fi