/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/com.huawei.switchos.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/com.huawei.switchosAdaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/com.huawei.switchos.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_HUAWEI_SWITCHOSADAPTOR_H
#define COM_HUAWEI_SWITCHOSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/com.huawei.switchos.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.huawei.switchos
 */
class SwitchosAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.huawei.switchos")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.huawei.switchos\">\n"
"    <method name=\"isDualOsSwitchAvail\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"isAvail\"/>\n"
"    </method>\n"
"    <method name=\"getOsFlag\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"flag\"/>\n"
"    </method>\n"
"    <method name=\"setOsFlag\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"flag\"/>\n"
"      <arg direction=\"out\" type=\"u\" name=\"result\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SwitchosAdaptor(QObject *parent);
    virtual ~SwitchosAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    uchar getOsFlag();
    uchar isDualOsSwitchAvail();
    uint setOsFlag(uchar flag);
Q_SIGNALS: // SIGNALS
};

#endif
