/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.Authenticate1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Authenticate1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Authenticate1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Authenticate1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Authenticate1Adaptor
 */

Authenticate1Adaptor::Authenticate1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Authenticate1Adaptor::~Authenticate1Adaptor()
{
    // destructor
}

int Authenticate1Adaptor::frameworkState() const
{
    // get the value of property FrameworkState
    return qvariant_cast< int >(parent()->property("FrameworkState"));
}

QString Authenticate1Adaptor::supportEncrypts() const
{
    // get the value of property SupportEncrypts
    return qvariant_cast< QString >(parent()->property("SupportEncrypts"));
}

int Authenticate1Adaptor::supportedFlags() const
{
    // get the value of property SupportedFlags
    return qvariant_cast< int >(parent()->property("SupportedFlags"));
}

QString Authenticate1Adaptor::Authenticate(const QString &username, int authFlags, int appType)
{
    // handle method call org.deepin.dde.Authenticate1.Authenticate
    QString path;
    QMetaObject::invokeMethod(parent(), "Authenticate", Q_RETURN_ARG(QString, path), Q_ARG(QString, username), Q_ARG(int, authFlags), Q_ARG(int, appType));
    return path;
}

QString Authenticate1Adaptor::GetLimits(const QString &username)
{
    // handle method call org.deepin.dde.Authenticate1.GetLimits
    QString limits;
    QMetaObject::invokeMethod(parent(), "GetLimits", Q_RETURN_ARG(QString, limits), Q_ARG(QString, username));
    return limits;
}

QString Authenticate1Adaptor::PreOneKeyLogin(int flag)
{
    // handle method call org.deepin.dde.Authenticate1.PreOneKeyLogin
    QString result;
    QMetaObject::invokeMethod(parent(), "PreOneKeyLogin", Q_RETURN_ARG(QString, result), Q_ARG(int, flag));
    return result;
}

