/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.SoundThemePlayer1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SoundThemePlayer1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SoundThemePlayer1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_SOUNDTHEMEPLAYER1ADAPTOR_H
#define ORG_DEEPIN_DDE_SOUNDTHEMEPLAYER1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SoundThemePlayer1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.SoundThemePlayer1
 */
class SoundThemePlayer1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.SoundThemePlayer1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.SoundThemePlayer1\">\n"
"    <method name=\"EnableSound\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"EnableSoundDesktopLogin\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"Play\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"theme\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"event\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"device\"/>\n"
"    </method>\n"
"    <method name=\"PlaySoundDesktopLogin\"/>\n"
"    <method name=\"PrepareShutdownSound\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"uid\"/>\n"
"    </method>\n"
"    <method name=\"SaveAudioState\">\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"avtivePlayback\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"SetSoundTheme\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"theme\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SoundThemePlayer1Adaptor(QObject *parent);
    virtual ~SoundThemePlayer1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void EnableSound(const QString &name, bool enabled);
    void EnableSoundDesktopLogin(bool enabled);
    void Play(const QString &theme, const QString &event, const QString &device);
    void PlaySoundDesktopLogin();
    void PrepareShutdownSound(int uid);
    void SaveAudioState(const QVariantMap &avtivePlayback);
    void SetSoundTheme(const QString &theme);
Q_SIGNALS: // SIGNALS
};

#endif
