/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.PowerManager1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.PowerManager1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.PowerManager1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.PowerManager1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PowerManager1Adaptor
 */

PowerManager1Adaptor::PowerManager1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PowerManager1Adaptor::~PowerManager1Adaptor()
{
    // destructor
}

bool PowerManager1Adaptor::CanHibernate()
{
    // handle method call org.deepin.dde.PowerManager1.CanHibernate
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanHibernate", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool PowerManager1Adaptor::CanReboot()
{
    // handle method call org.deepin.dde.PowerManager1.CanReboot
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanReboot", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool PowerManager1Adaptor::CanShutdown()
{
    // handle method call org.deepin.dde.PowerManager1.CanShutdown
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanShutdown", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool PowerManager1Adaptor::CanSuspend()
{
    // handle method call org.deepin.dde.PowerManager1.CanSuspend
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanSuspend", Q_RETURN_ARG(bool, out0));
    return out0;
}

