/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.freedesktop.login1.session.self.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.freedesktop.login1.session.selfAdaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.freedesktop.login1.session.self.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_LOGIN1_SESSION_SELFADAPTOR_H
#define ORG_FREEDESKTOP_LOGIN1_SESSION_SELFADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.freedesktop.login1.session.self.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.login1.Session
 */
class SessionAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.login1.Session")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.login1.Session\">\n"
"    <method name=\"Activate\"/>\n"
"    <method name=\"Lock\"/>\n"
"    <method name=\"Terminate\"/>\n"
"    <method name=\"Unlock\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Active\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Desktop\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Display\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Id\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Name\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Type\"/>\n"
"  </interface>\n"
        "")
public:
    SessionAdaptor(QObject *parent);
    virtual ~SessionAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool Active READ active)
    bool active() const;

    Q_PROPERTY(QString Desktop READ desktop)
    QString desktop() const;

    Q_PROPERTY(QString Display READ display)
    QString display() const;

    Q_PROPERTY(QString Id READ id)
    QString id() const;

    Q_PROPERTY(QString Name READ name)
    QString name() const;

public Q_SLOTS: // METHODS
    void Activate();
    void Lock();
    void Terminate();
    void Unlock();
Q_SIGNALS: // SIGNALS
};

#endif
