/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.ImageEffect1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageEffect1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageEffect1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_IMAGEEFFECT1ADAPTOR_H
#define ORG_DEEPIN_DDE_IMAGEEFFECT1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageEffect1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.ImageEffect1
 */
class ImageEffect1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.ImageEffect1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.ImageEffect1\">\n"
"    <method name=\"Delete\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"effect\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\"/>\n"
"    </method>\n"
"    <method name=\"Get\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"effect\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"outputFile\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ImageEffect1Adaptor(QObject *parent);
    virtual ~ImageEffect1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Delete(const QString &effect, const QString &filename);
    QString Get(const QString &effect, const QString &filename);
Q_SIGNALS: // SIGNALS
};

#endif
