/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.Logined.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.LoginedAdaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Logined.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_LOGINEDADAPTOR_H
#define ORG_DEEPIN_DDE_LOGINEDADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Logined.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Logined
 */
class LoginedAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Logined")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Logined\">\n"
"    <property access=\"read\" type=\"s\" name=\"UserList\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"LastLogoutUser\"/>\n"
"  </interface>\n"
        "")
public:
    LoginedAdaptor(QObject *parent);
    virtual ~LoginedAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint LastLogoutUser READ lastLogoutUser)
    uint lastLogoutUser() const;

    Q_PROPERTY(QString UserList READ userList)
    QString userList() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
