/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.freedesktop.login1.session.self.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.freedesktop.login1.session.selfAdaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.freedesktop.login1.session.self.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.freedesktop.login1.session.selfAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SessionAdaptor
 */

SessionAdaptor::SessionAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SessionAdaptor::~SessionAdaptor()
{
    // destructor
}

bool SessionAdaptor::active() const
{
    // get the value of property Active
    return qvariant_cast< bool >(parent()->property("Active"));
}

QString SessionAdaptor::desktop() const
{
    // get the value of property Desktop
    return qvariant_cast< QString >(parent()->property("Desktop"));
}

QString SessionAdaptor::display() const
{
    // get the value of property Display
    return qvariant_cast< QString >(parent()->property("Display"));
}

QString SessionAdaptor::id() const
{
    // get the value of property Id
    return qvariant_cast< QString >(parent()->property("Id"));
}

QString SessionAdaptor::name() const
{
    // get the value of property Name
    return qvariant_cast< QString >(parent()->property("Name"));
}

void SessionAdaptor::Activate()
{
    // handle method call org.freedesktop.login1.Session.Activate
    QMetaObject::invokeMethod(parent(), "Activate");
}

void SessionAdaptor::Lock()
{
    // handle method call org.freedesktop.login1.Session.Lock
    QMetaObject::invokeMethod(parent(), "Lock");
}

void SessionAdaptor::Terminate()
{
    // handle method call org.freedesktop.login1.Session.Terminate
    QMetaObject::invokeMethod(parent(), "Terminate");
}

void SessionAdaptor::Unlock()
{
    // handle method call org.freedesktop.login1.Session.Unlock
    QMetaObject::invokeMethod(parent(), "Unlock");
}

