/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.Authenticate1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Authenticate1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Authenticate1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_AUTHENTICATE1ADAPTOR_H
#define ORG_DEEPIN_DDE_AUTHENTICATE1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.Authenticate1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Authenticate1
 */
class Authenticate1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Authenticate1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Authenticate1\">\n"
"    <property access=\"read\" type=\"i\" name=\"SupportedFlags\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"FrameworkState\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"SupportEncrypts\"/>\n"
"    <signal name=\"LimitUpdated\">\n"
"      <arg type=\"s\"/>\n"
"    </signal>\n"
"    <method name=\"PreOneKeyLogin\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"flag\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"GetLimits\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"limits\"/>\n"
"    </method>\n"
"    <method name=\"Authenticate\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"authFlags\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"appType\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    Authenticate1Adaptor(QObject *parent);
    virtual ~Authenticate1Adaptor();

public: // PROPERTIES
    Q_PROPERTY(int FrameworkState READ frameworkState)
    int frameworkState() const;

    Q_PROPERTY(QString SupportEncrypts READ supportEncrypts)
    QString supportEncrypts() const;

    Q_PROPERTY(int SupportedFlags READ supportedFlags)
    int supportedFlags() const;

public Q_SLOTS: // METHODS
    QString Authenticate(const QString &username, int authFlags, int appType);
    QString GetLimits(const QString &username);
    QString PreOneKeyLogin(int flag);
Q_SIGNALS: // SIGNALS
    void LimitUpdated(const QString &in0);
};

#endif
