/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.SystemDisplay1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemDisplay1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemDisplay1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemDisplay1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Display1Adaptor
 */

Display1Adaptor::Display1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Display1Adaptor::~Display1Adaptor()
{
    // destructor
}

QString Display1Adaptor::GetConfig()
{
    // handle method call org.deepin.dde.Display1.GetConfig
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetConfig", Q_RETURN_ARG(QString, out0));
    return out0;
}

void Display1Adaptor::SetConfig(const QString &in0)
{
    // handle method call org.deepin.dde.Display1.SetConfig
    QMetaObject::invokeMethod(parent(), "SetConfig", Q_ARG(QString, in0));
}

