/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.ImageEffect1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageEffect1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageEffect1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageEffect1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ImageEffect1Adaptor
 */

ImageEffect1Adaptor::ImageEffect1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ImageEffect1Adaptor::~ImageEffect1Adaptor()
{
    // destructor
}

void ImageEffect1Adaptor::Delete(const QString &effect, const QString &filename)
{
    // handle method call org.deepin.dde.ImageEffect1.Delete
    QMetaObject::invokeMethod(parent(), "Delete", Q_ARG(QString, effect), Q_ARG(QString, filename));
}

QString ImageEffect1Adaptor::Get(const QString &effect, const QString &filename)
{
    // handle method call org.deepin.dde.ImageEffect1.Get
    QString outputFile;
    QMetaObject::invokeMethod(parent(), "Get", Q_RETURN_ARG(QString, outputFile), Q_ARG(QString, effect), Q_ARG(QString, filename));
    return outputFile;
}

