/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-shell/xml/org.deepin.dde.SystemDisplay1.xml -a ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemDisplay1Adaptor -i ./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemDisplay1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_SYSTEMDISPLAY1ADAPTOR_H
#define ORG_DEEPIN_DDE_SYSTEMDISPLAY1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-shell/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemDisplay1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Display1
 */
class Display1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Display1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Display1\">\n"
"    <method name=\"GetConfig\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"SetConfig\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <signal name=\"ConfigUpdated\">\n"
"      <arg type=\"s\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    Display1Adaptor(QObject *parent);
    virtual ~Display1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetConfig();
    void SetConfig(const QString &in0);
Q_SIGNALS: // SIGNALS
    void ConfigUpdated(const QString &in0);
};

#endif
